### ISSUE TITLE
Bug: WindowsSessionUser forces username to be in SAM Account Name format

### ISSUE THREAD

**Issue by Ahuge** [OpenJobDescription/openjd-sessions-for-python#142]
### Expected Behaviour

I have passed in a username to WindowsSessionUser such as `alex@company.com` because my active directory requires the UPN name instead of a legacy SAM Account Name format. The WindowsSessionUser calls `TranslateName` to convert it from UPN into SAM.

Tracking down what is done with the username (now in SAM format), it doesn't seem to require it to be in SAM format because it calls `CreateProcessWithLogonW` which fully supports UPN.
I would expect it to respect my username format and keep it in UPN.

### Current Behaviour

Currently WindowsSessionUser will convert it to SAM Account name if it is in UPN and the computer is domain joined.

This causes a `(5, 'TranslateName', 'Access is denied.')` error for me and makes me unable to use custom worker users in DeadlineCloudWorker.

### Reproduction Steps

The domain that my client is using doesn't support SAM account name when trying to use the `win32security.LogonUser` call. We kept getting username or password is invalid error from `win32security`. 
During my testing I determined that using the UPN name allows `win32security.LogonUser` to work without issue.

Because of this limitation on their AD, the `win32security.LogonUser` to convert it back to SAM Account name is causing issues for me. 
Do you know why this `TranslateName` call is needed?

### Code Snippet

https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/beeb4992dfc37ee2532fb79083819f285f4cfafc/src/openjd/sessions/_session_user.py#L174-L177

**Comment by ddneilson** [comment]
Thanks for the report, Alex! The TranslateName does, indeed, appear to be superfluous. I'll get rid of it.
