### ISSUE TITLE
Bug: Running tasks on Windows depends on PowerShell 7+

### ISSUE THREAD

**Issue by mwiebe** [OpenJobDescription/openjd-sessions-for-python#46]
### Expected Behaviour

It should be possible to run sessions on a default Windows 10 install, that only includes PowerShell 5.1, not 7.

At the very least, the error message should be clear about the problem.  Currently it produces an error messages that "pwsh.exe" is not found.

### Current Behaviour

Cannot run sessions on Windows 10.

### Reproduction Steps

Start from a Windows 10 machine that has only the default PowerShell installed. Try to run a task with the `openjd run` CLI command.

**Comment by ddneilson** [comment]
Thank you for the report. Powershell, of any version, is no longer required.
